language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3
env:
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:16.04
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=ubuntu:16.04
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=ubuntu:16.04
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=ubuntu:16.04
- ANSIBLE_VERSIONS=2.5.1 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=2.5.1 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=2.5.1 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=2.5.1 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=2.5.1 DOCKER_IMAGES=ubuntu:16.04
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh
after_failure:
- cat role-tester-ansible-master/.kitchen.yml
- cat role-tester-ansible-master/.kitchen.local.yml
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: KBi/5t4Qnb3FUWob5yl0gHuvYAaOQovwXckgvKb4pVBkFaF/75HgkSCTvCLEQLHnaHBeHscTPqOBVtqJZD2eiR7f7niLv9ZOBnVBp6jA0yE3mCRsmmTEt91ukoUWTEEd+mbC97TIzkmZ2L//P501DB9k9HYxPwCmDtpulqNQMUs/wyJuq74M1qZjMgk5ca1gbo/+xuBP3PJ70ODpjPm/xZLQ5kr/Ml8SiZrBmsiWj7HPdARAYWIi1LIcWzjQ2Rj4V7DxqQ60uc+h9ecqIBtfC+RC2oatKl/EGlbjcILhsxS74qZK+di/Hr8y4iupmWfBzqCXTM0k/Ei73N2/GodV0olFawjFti02dPolDJw07Tf3v2ucyYNwRmUK4rRW4pfKufDlQvQmjXtwMbthZUxZQ1qW1HkN7i/uIv9Oa+huVEy2P3IIcolkVnxWo3FH+0wYoyz3fgJRPCQfDcTs113W3wWp93a+iTiTaiVeh9lCRilI5M23fHbXC/tGcqMpwE/B4g9X2sKRJvrtHqs3mrVOqNLfynll5Mxs7UK4mwE/bobL9xIHmHTjY3nW/O3WO4CbXDDll3nB0tb5J+h7EG0n0vdQO+DWvPcsi390kyIXjE1RZNknfmn0O8ng8e23t4KdsP4JO+lmnIj5mncNkzPEZqqefNAtl6aTPqXxCuqigZ8=
  email:
    recipients:
      secure: a57YWOXaZZInxrshaNhkR6Wst77y4rUbeZ8C8miycPSI5KV4fuWHlDPOa0b61qHp1Wf8Oh9gKpsR04lZqcRWRVt5ORUq6o1XQmdBVZm/jI4gWQgG8u6XoP2DX3g6bPjtfY8y0h5rRUMciy6cO9bIAzWBvF8qNvdmJVzz/g7jwwkOYhd3CeJx5q0Z4MUIDEZWOZb6a0a9uUdHtHw91p0uU05Owmhti3JxVcxts14eHalquBEjgcFlNXmI3b3c91NFq53CIFf7KXhP2mlh9u/Khb8a4L+arXF/6a7d/1QaMWp0ikCy8voMvmF+7EHplwy+1Jrh8yI+g8lJnFmXvhVCW1WrN1+/VvHD26InLoDfx44WHneICdEh242AhueHXRWUxQORX2npYZabtYmGdWeWXq9bwiXxs2we5OiSvhrIFli5b27cVG27tlDK5PXkmVL3VD42bXBeqDcf9EJ9Ik9mCFkKUTg3nkr7xRuYZlSF7cVj55IFLtYr/8Z1fij+koejAQubp9Lg6oj51Q0YADLFN63Q3ndNOcsB3KVYRFN0dmBANUppeSyogIcINoO9aoVsAXOWdVB1ASeDM1k4sQ4ATX1D9SnpzO3dksc30jr/9tjBpX5J3MJ9/9rmcBPX+KPZ79YBtlwKfQMa8RZcy86EWnZK1lgHF1Nq3yGlH9Jrqvs=
